# Generated by Django 5.2.4 on 2025-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_player_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
