# Generated by Django 5.2.4 on 2025-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_additem'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='item_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
