# Generated by Django 5.2.4 on 2025-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_additem_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additem",
            name="item_image",
            field=models.ImageField(upload_to="shop_items/"),
        ),
    ]
